import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, FileText, LockKeyhole, RefreshCw, ShieldCheck, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { getSuperAdminDashboard } from '../lib/superAdmin';
import type { SuperAdminDashboard as DashboardData, SuperAdminRecord } from '../types';

export const SuperAdminDashboard = () => {
  const navigate = useNavigate();
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<SuperAdminRecord | null>(null);
  const [query, setQuery] = useState('');
  const load = async () => { setLoading(true); setData(await getSuperAdminDashboard()); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const records = useMemo(() => (data?.records ?? []).filter(record => `${record.nickname} ${record.email} ${record.topic}`.toLowerCase().includes(query.toLowerCase())), [data, query]);

  return <main className="app-container page-scroll" style={{ padding: '2rem 1.25rem 4rem', maxWidth: 1180 }}>
    <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem', marginBottom: '1.5rem' }}><div><button className="btn btn-secondary" style={{ padding: '.45rem .7rem', marginBottom: '.7rem' }} onClick={() => navigate('/')}><ChevronLeft size={16} /> ThinkFit</button><h1 style={{ margin: 0 }}><ShieldCheck color="var(--primary)" style={{ verticalAlign: 'middle' }} /> 슈퍼 관리자</h1><p style={{ margin: '.4rem 0 0', color: 'var(--text-muted)' }}>개발자 전용 · 전체 회원 활동 기록</p></div><button className="icon-button" onClick={() => void load()} title="새로고침"><RefreshCw size={18} /></button></header>
    {loading ? <p style={{ textAlign: 'center', padding: '4rem', color: 'var(--text-muted)' }}>권한과 활동 기록을 확인하는 중입니다.</p> : !data ? <section className="card" style={{ textAlign: 'center', padding: '3rem' }}><LockKeyhole size={36} color="var(--secondary)" /><h2>접근 권한이 없습니다</h2><p style={{ color: 'var(--text-muted)' }}>서버에서 슈퍼 관리자 이메일을 확인하지 못했습니다.</p></section> : <>
      <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))', gap: '1rem' }}><Metric icon={<Users />} label="전체 회원" value={`${data.totalUsers}명`} /><Metric icon={<FileText />} label="전체 토론 기록" value={`${data.totalRecords}건`} /><Metric icon={<ShieldCheck />} label="활동 회원" value={`${data.activeUsers}명`} /></section>
      <section className="card" style={{ padding: '1.3rem', marginTop: '1rem' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', flexWrap: 'wrap', alignItems: 'center' }}><h2 style={{ margin: 0 }}>전체 활동 기록</h2><input className="input-field" placeholder="회원명 · 이메일 · 토론 주제 검색" value={query} onChange={event => setQuery(event.target.value)} style={{ maxWidth: 300 }} /></div><div style={{ overflowX: 'auto', marginTop: '1rem' }}><table style={{ width: '100%', minWidth: 760, borderCollapse: 'collapse' }}><thead><tr>{['회원', '이메일', '토론 주제', '수준', '점수', '완료일', ''].map(label => <th key={label} style={headStyle}>{label}</th>)}</tr></thead><tbody>{records.map(record => <tr key={record.id}><td style={cellStyle}>{record.nickname}</td><td style={cellStyle}>{record.email}</td><td style={cellStyle}>{record.topic}</td><td style={cellStyle}>{record.debateLevel === 'beginner' ? '초급' : record.debateLevel === 'intermediate' ? '중급' : '고급'}</td><td style={cellStyle}>{record.totalScore}점</td><td style={cellStyle}>{new Date(record.completedAt).toLocaleString('ko-KR')}</td><td style={cellStyle}><button className="btn btn-secondary" style={{ padding: '.4rem .6rem' }} onClick={() => setSelected(record)}>보고서</button></td></tr>)}</tbody></table></div>{!records.length && <p style={{ textAlign: 'center', color: 'var(--text-muted)', padding: '2rem' }}>표시할 토론 기록이 없습니다.</p>}</section>
    </>}
    {selected && <div role="dialog" aria-modal="true" style={{ position: 'fixed', inset: 0, zIndex: 30, background: 'rgba(0,0,0,.6)', overflowY: 'auto', padding: '2rem 1rem' }}><article className="card" style={{ maxWidth: 760, margin: 'auto', padding: '1.5rem' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem' }}><div><h2 style={{ margin: 0 }}>{selected.topic}</h2><p style={{ color: 'var(--text-muted)' }}>{selected.nickname} · {selected.email}</p></div><button className="icon-button" onClick={() => setSelected(null)}>×</button></div><section style={{ marginTop: '1.2rem' }}><h3>AI 총평</h3><p style={{ lineHeight: 1.7, color: 'var(--text-muted)' }}>{selected.report?.overallFeedback || '저장된 총평이 없습니다.'}</p></section><section><h3>세부 역량</h3>{selected.report?.categories?.map(category => <article key={category.name} style={{ borderTop: '1px solid var(--border)', padding: '.75rem 0' }}><strong>{category.name} · {category.score}/{category.maxScore}</strong><p style={{ marginBottom: 0, color: 'var(--text-muted)' }}>{category.feedback}</p></article>)}</section><section><h3>토론 발언 기록</h3>{selected.arguments?.map(argument => <article key={argument.id} style={{ borderLeft: `3px solid ${argument.isAi ? 'var(--text-muted)' : 'var(--primary)'}`, padding: '.6rem .8rem', marginBottom: '.6rem', background: 'rgba(255,255,255,.03)' }}><strong>{argument.isAi ? 'AI' : selected.nickname}{argument.roundTitle ? ` · ${argument.roundTitle}` : ''}</strong><p style={{ marginBottom: 0, whiteSpace: 'pre-wrap' }}>{argument.content}</p></article>)}</section></article></div>}
  </main>;
};
const Metric = ({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) => <article className="card" style={{ padding: '1.1rem' }}><span style={{ color: 'var(--primary)' }}>{icon}</span><p style={{ margin: '.5rem 0 .1rem', color: 'var(--text-muted)' }}>{label}</p><strong style={{ fontSize: '1.55rem' }}>{value}</strong></article>;
const headStyle = { textAlign: 'left' as const, padding: '.7rem .5rem', color: 'var(--text-muted)', borderBottom: '1px solid var(--border)' };
const cellStyle = { padding: '.8rem .5rem', borderBottom: '1px solid var(--border)' };
